title: Gaurang Tandon
email: gaurangtandonone at gmail
description: I write about tech stuff.
baseurl: ""
url: gaurangtandon.com
source: https://github.com/gaurangtandon/gaurangtandon.github.io
twitter_username: alltimecoder
github_username:  gaurangtandon

# Build settings
theme: minima
plugins:
  - jekyll-feed
future: true # https://stackoverflow.com/a/35388975/2181238

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
