title: Gaurang Tandon
email: 1gaurangtandon at gmail
description: >- # this means to ignore newlines until "baseurl:"
    Gaurang's descriptions of tech, culture and general
baseurl: "" # the subpath of your site, e.g. /blog
url: gaurangtandon.github.io
source: https://github.com/gaurangtandon/gaurangtandon.github.io
twitter_username: alltimecoder
github_username:  gaurangtandon

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
